# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

formats:
- htmlzip

build:
  os: ubuntu-22.04
  tools:
    # Use most recent version supported by Numba
    python: '3.10'
  apt_packages:
  - graphviz
  jobs:
    pre_create_environment:
    - python -m pip install --upgrade setuptools pip
    post_build:
    - echo https://docs.plasmapy.org/en/latest/contributing/doc_guide.html#troubleshooting

python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
  system_packages: true
