# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

formats:
- htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  apt_packages:
  - graphviz
  jobs:
    post_build:
    - echo $'\n'For help deciphering documentation build error messages, see:$'\n\n'\ \ https://docs.plasmapy.org/en/latest/contributing/doc_guide.html#troubleshooting

python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
