name: CI

on:
  push:
    branches:
    - main
    - stable
    - v*.*.x
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: py311
        - macos: py310
        - windows: py39
        - linux: build_docs
          libraries:
            apt:
            - pandoc
          with:
            PYDEVD_DISABLE_FILE_VALIDATION: 1

#      coverage: 'codecov'
#    secrets:
#      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
