name: weekly tests

on:
  schedule:
  - cron: 17 7 * * 1
  workflow_dispatch:

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:

        - name: Python 3.8 with Astropy dev
          os: ubuntu-latest
          python: 3.8
          toxenv: py38-astropydev

        - name: Python 3.8 with NumPy dev
          os: ubuntu-latest
          python: 3.8
          toxenv: py38-numpydev

        - name: Python 3.8 with sunpy dev
          os: ubuntu-latest
          python: 3.8
          toxenv: py38-sunpydev

        - name: Documentation with Sphinx dev
          os: ubuntu-latest
          python: 3.8
          toxenv: build_docs-sphinxdev
          toxposargs: -q

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.5
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox codecov
    - name: Install language-pack-fr and tzdata
      if: startsWith(matrix.name, 'Documentation')
      run: sudo apt-get install graphviz pandoc
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
    - name: Upload coverage to codecov
      if: ${{ contains(matrix.toxenv,'-cov') }}
      uses: codecov/codecov-action@v2.1.0
      with:
        file: ./coverage.xml
